import type { RoomStyleSpec, SampleRoom } from "./types";

/** A deliberately dated / tired room used as the "before" state. */
const NINETIES: RoomStyleSpec = {
  wall: "#CFC5AE",
  wallAccent: "#C4B89D",
  panel: "none",
  floor: "#A5794A",
  floorSeam: "#8A6238",
  rug: "#8F7B5E",
  rugAccent: "#7A684E",
  sofa: "#6B5138",
  sofaShadow: "#4E3A27",
  cushions: ["#8F7B5E", "#4E3A27", "#A38F6E"],
  wood: "#6E4F32",
  metal: "#55524A",
  lampGlow: "#F5E1B8",
  windowLight: "#DDE3E0",
  art: "none",
  artColors: ["#7A684E"],
  plant: false,
  pendant: false,
  warmth: 0.3,
};

const RENTAL: RoomStyleSpec = {
  wall: "#DAD7CE",
  wallAccent: "#CFCCC2",
  panel: "none",
  floor: "#C9B68F",
  floorSeam: "#B29E76",
  rug: "#9FA0A2",
  rugAccent: "#8C8D90",
  sofa: "#7C7E82",
  sofaShadow: "#5F6165",
  cushions: ["#9FA0A2", "#54565A"],
  wood: "#A9895B",
  metal: "#6E6F72",
  lampGlow: "#F2EAD6",
  windowLight: "#E4E9E7",
  art: "none",
  artColors: ["#8C8D90"],
  plant: false,
  pendant: false,
  warmth: 0.15,
};

const DEN: RoomStyleSpec = {
  wall: "#C8BC96",
  wallAccent: "#BBAE85",
  panel: "none",
  floor: "#96683C",
  floorSeam: "#7C5530",
  rug: "#8A5B3A",
  rugAccent: "#6F4A2F",
  sofa: "#59503C",
  sofaShadow: "#413A2C",
  cushions: ["#8A5B3A", "#41442E", "#A08A5C"],
  wood: "#5E4326",
  metal: "#4E4A3E",
  lampGlow: "#F1DFB4",
  windowLight: "#DFE2D8",
  art: "none",
  artColors: ["#6F4A2F"],
  plant: false,
  pendant: false,
  warmth: 0.35,
};

export const SAMPLE_ROOMS: SampleRoom[] = [
  {
    id: "city-apartment",
    name: "City Apartment",
    meta: "Living room · ~24 m² · West light",
    spec: NINETIES,
    analysis: {
      engine: "demo",
      roomType: "Living room",
      confidence: 0.97,
      summary:
        "A generously proportioned living room with strong west-facing light and honey-oak floors in good condition. The 1990s beige envelope and heavy dark furniture absorb most of that light — the bones deserve far better.",
      dimensions: { widthM: 5.6, depthM: 4.3, heightM: 2.7, areaM2: 24.1 },
      walls: { count: 4, condition: "Good — minor scuffing", finish: "Beige matte paint" },
      windows: { count: 1, orientation: "West", naturalLight: "Strong afternoon sun" },
      doors: { count: 1, note: "Entry from hallway, right of frame" },
      flooring: { material: "Solid oak strip", tone: "Honey / orange", condition: "Good, refinishable" },
      lighting: { naturalScore: 78, artificial: "Single floor lamp — underlit", colorTemperature: "Warm 2700K" },
      colorPalette: [
        { hex: "#CFC5AE", name: "Dated beige" },
        { hex: "#6B5138", name: "Heavy walnut" },
        { hex: "#A5794A", name: "Honey oak" },
        { hex: "#8F7B5E", name: "Worn taupe" },
      ],
      materials: ["Oak flooring", "Latex paint", "Polyester upholstery", "Laminate side furniture"],
      furniture: [
        { item: "Three-seat fabric sofa", condition: "Worn", verdict: "Replace" },
        { item: "Dark-stain coffee table", condition: "Fair", verdict: "Replace" },
        { item: "Area rug", condition: "Flattened pile", verdict: "Replace" },
        { item: "Floor lamp", condition: "Working", verdict: "Rework placement" },
      ],
      detections: [
        { label: "Sofa", detail: "Three-seat, worn fabric", confidence: 0.98, box: { x: 0.34, y: 0.58, w: 0.31, h: 0.24 } },
        { label: "Window", detail: "West-facing, ~1.6m", confidence: 0.96, box: { x: 0.04, y: 0.18, w: 0.2, h: 0.42 } },
        { label: "Oak flooring", detail: "Strip, honey tone", confidence: 0.94, box: { x: 0.12, y: 0.74, w: 0.76, h: 0.24 } },
        { label: "Coffee table", detail: "Dark stain, dated", confidence: 0.92, box: { x: 0.42, y: 0.8, w: 0.17, h: 0.11 } },
      ],
      opportunities: [
        "West light is the room's best asset — lighten wall value to amplify it",
        "Float the sofa off the wall to create a conversation zone",
        "Layer three light sources to replace the single-lamp scheme",
        "Rug is undersized; a 250cm rug will anchor the seating area",
      ],
      styleAffinity: [
        { styleId: "scandinavian", score: 94 },
        { styleId: "japandi", score: 91 },
        { styleId: "midcentury", score: 86 },
        { styleId: "coastal", score: 78 },
      ],
    },
  },
  {
    id: "rental-flat",
    name: "Rental Flat",
    meta: "Living room · ~18 m² · North light",
    spec: RENTAL,
    analysis: {
      engine: "demo",
      roomType: "Living room",
      confidence: 0.96,
      summary:
        "A compact rental with cool north light, builder-grade greige walls and laminate floors. Everything reads temporary. The fix is texture and warmth, not construction — ideal for a renter-safe transformation.",
      dimensions: { widthM: 4.8, depthM: 3.7, heightM: 2.5, areaM2: 17.8 },
      walls: { count: 4, condition: "Good — rental white", finish: "Greige eggshell" },
      windows: { count: 1, orientation: "North", naturalLight: "Even, cool, diffuse" },
      doors: { count: 1, note: "Single entry, no hallway buffer" },
      flooring: { material: "Laminate plank", tone: "Light sand", condition: "Good" },
      lighting: { naturalScore: 55, artificial: "Ceiling fixture only — flat", colorTemperature: "Cool 4000K" },
      colorPalette: [
        { hex: "#DAD7CE", name: "Rental greige" },
        { hex: "#7C7E82", name: "Flat grey" },
        { hex: "#C9B68F", name: "Sand laminate" },
        { hex: "#9FA0A2", name: "Cool putty" },
      ],
      materials: ["Laminate flooring", "Eggshell paint", "Microfibre upholstery"],
      furniture: [
        { item: "Two-seat grey sofa", condition: "Fair", verdict: "Replace or slipcover" },
        { item: "Grey area rug", condition: "Thin", verdict: "Replace" },
        { item: "No coffee table", condition: "—", verdict: "Add" },
      ],
      detections: [
        { label: "Sofa", detail: "Two-seat, microfibre", confidence: 0.97, box: { x: 0.36, y: 0.6, w: 0.28, h: 0.22 } },
        { label: "Window", detail: "North-facing", confidence: 0.95, box: { x: 0.05, y: 0.2, w: 0.18, h: 0.4 } },
        { label: "Laminate floor", detail: "Sand tone plank", confidence: 0.93, box: { x: 0.1, y: 0.75, w: 0.8, h: 0.23 } },
      ],
      opportunities: [
        "Cool north light wants warm textiles and 2700K lamps to balance",
        "Vertical storage will free floor area in the compact footprint",
        "A tactile rug adds the warmth the laminate can't",
        "Renter-safe: no paint required if textiles carry the palette",
      ],
      styleAffinity: [
        { styleId: "japandi", score: 92 },
        { styleId: "scandinavian", score: 90 },
        { styleId: "bohemian", score: 84 },
        { styleId: "minimalist", score: 80 },
      ],
    },
  },
  {
    id: "family-den",
    name: "Family Den",
    meta: "Living room · ~29 m² · South light",
    spec: DEN,
    analysis: {
      engine: "demo",
      roomType: "Living room / den",
      confidence: 0.95,
      summary:
        "A large, sun-drenched family room with great southern exposure and character oak floors under two decades of olive-and-brown layering. High ceilings and big proportions can carry a dramatic scheme.",
      dimensions: { widthM: 6.4, depthM: 4.6, heightM: 2.9, areaM2: 29.4 },
      walls: { count: 4, condition: "Fair — nail holes, sun fade", finish: "Olive-beige satin" },
      windows: { count: 2, orientation: "South", naturalLight: "Abundant all day" },
      doors: { count: 2, note: "Double doors to garden, hallway entry" },
      flooring: { material: "Character oak plank", tone: "Amber", condition: "Scratched — refinishable" },
      lighting: { naturalScore: 88, artificial: "Mixed dated fixtures", colorTemperature: "Mixed 2700–4000K" },
      colorPalette: [
        { hex: "#C8BC96", name: "Faded olive" },
        { hex: "#59503C", name: "Umber sofa" },
        { hex: "#96683C", name: "Amber oak" },
        { hex: "#8A5B3A", name: "Rust rug" },
      ],
      materials: ["Character oak", "Satin paint", "Chenille upholstery", "Brass-plate hardware"],
      furniture: [
        { item: "Sectional sofa", condition: "Sagging", verdict: "Replace" },
        { item: "Oak coffee table", condition: "Scratched", verdict: "Refinish or replace" },
        { item: "Rust area rug", condition: "Sun-faded", verdict: "Replace" },
        { item: "Media cabinet", condition: "Good", verdict: "Keep" },
      ],
      detections: [
        { label: "Sectional", detail: "L-shape, chenille", confidence: 0.97, box: { x: 0.3, y: 0.56, w: 0.36, h: 0.27 } },
        { label: "Windows", detail: "South pair", confidence: 0.96, box: { x: 0.03, y: 0.16, w: 0.22, h: 0.46 } },
        { label: "Oak plank floor", detail: "Amber, scratched", confidence: 0.94, box: { x: 0.08, y: 0.72, w: 0.84, h: 0.26 } },
        { label: "Media cabinet", detail: "Solid oak, keep", confidence: 0.9, box: { x: 0.68, y: 0.5, w: 0.2, h: 0.16 } },
      ],
      opportunities: [
        "2.9m ceilings + south light can carry a deep, saturated palette",
        "Zone the 29m² into seating + reading corner instead of one block",
        "Keep the solid-oak media cabinet — refinish to match new scheme",
        "Sheer + blackout layering will tame afternoon glare",
      ],
      styleAffinity: [
        { styleId: "artdeco", score: 93 },
        { styleId: "midcentury", score: 90 },
        { styleId: "industrial", score: 85 },
        { styleId: "bohemian", score: 81 },
      ],
    },
  },
];

export const SAMPLE_ROOM_MAP: Record<string, SampleRoom> = Object.fromEntries(
  SAMPLE_ROOMS.map((r) => [r.id, r]),
);
