import type { DesignStyle, RoomStyleSpec } from "./types";

export const STYLES: DesignStyle[] = [
  {
    id: "scandinavian",
    name: "Scandinavian",
    tagline: "Light, calm, effortless",
    description:
      "Pale oak, soft whites and functional silhouettes. A room that breathes — built around daylight and quiet texture.",
    tags: ["Airy", "Pale oak", "Soft neutrals"],
    palette: ["#EDEAE2", "#D8CFC0", "#B9A98C", "#3D3A34"],
    budgetBand: "CHF 3.2k – 6.8k",
    spec: {
      wall: "#E9E5DC",
      wallAccent: "#DFD9CC",
      panel: "none",
      floor: "#D8C4A4",
      floorSeam: "#C2AC8A",
      rug: "#E3DDD0",
      rugAccent: "#C9C0AE",
      sofa: "#D6D1C6",
      sofaShadow: "#B8B2A5",
      cushions: ["#B9A98C", "#8F8B80", "#E9E5DC"],
      wood: "#C9A876",
      metal: "#3D3A34",
      lampGlow: "#FFE9C4",
      windowLight: "#EAF2F5",
      art: "line",
      artColors: ["#3D3A34", "#B9A98C"],
      plant: true,
      pendant: true,
      warmth: 0.25,
    },
  },
  {
    id: "japandi",
    name: "Japandi",
    tagline: "Wabi-sabi meets nordic restraint",
    description:
      "Low-slung forms, slatted wood and tea-stained neutrals. Every object earns its place; nothing shouts.",
    tags: ["Low profile", "Slatted wood", "Tea tones"],
    palette: ["#E4DCCB", "#B49B72", "#6E5B44", "#2E2A25"],
    budgetBand: "CHF 4.1k – 8.5k",
    spec: {
      wall: "#E2DACA",
      wallAccent: "#D3C6AE",
      panel: "slats",
      floor: "#B99971",
      floorSeam: "#96794F",
      rug: "#D8CDB6",
      rugAccent: "#B8A784",
      sofa: "#A79680",
      sofaShadow: "#84755F",
      cushions: ["#2E2A25", "#D8CDB6", "#6E5B44"],
      wood: "#8A6B44",
      metal: "#2E2A25",
      lampGlow: "#FFE3B8",
      windowLight: "#EDF0EA",
      art: "botanical",
      artColors: ["#6E5B44", "#2E2A25"],
      plant: true,
      pendant: true,
      warmth: 0.35,
    },
  },
  {
    id: "modernluxury",
    name: "Modern Luxury",
    tagline: "Cream bouclé, travertine, brass",
    description:
      "Hotel-suite serenity: sculptural cream upholstery, fluted walls, stone and warm metal. Quiet money, loud comfort.",
    tags: ["Bouclé", "Travertine", "Warm brass"],
    palette: ["#E8E2D6", "#DCCFB8", "#C8A96E", "#2E2B27"],
    budgetBand: "CHF 7.5k – 16k",
    spec: {
      wall: "#E8E2D6",
      wallAccent: "#DCD2C0",
      panel: "slats",
      floor: "#CDB894",
      floorSeam: "#B5A07C",
      rug: "#E6DFD2",
      rugAccent: "#C8A96E",
      sofa: "#E3DCCD",
      sofaShadow: "#C4BCAA",
      cushions: ["#C8A96E", "#8C8578", "#2E2B27"],
      wood: "#A98F63",
      metal: "#C8A96E",
      lampGlow: "#FFE9C0",
      windowLight: "#F0F2EF",
      art: "abstract",
      artColors: ["#C8A96E", "#8C8578"],
      plant: true,
      pendant: true,
      warmth: 0.35,
    },
  },
  {
    id: "minimalist",
    name: "Minimalist",
    tagline: "Nothing extra, everything intentional",
    description:
      "A near-monochrome envelope where proportion does the talking. Storage disappears; light and shadow furnish the room.",
    tags: ["Monochrome", "Hidden storage", "Negative space"],
    palette: ["#F2F1EE", "#DBD9D4", "#9E9C96", "#2B2B29"],
    budgetBand: "CHF 2.9k – 6.2k",
    spec: {
      wall: "#F0EEE9",
      wallAccent: "#E6E4DE",
      panel: "none",
      floor: "#DCD7CD",
      floorSeam: "#C6C0B4",
      rug: "#E9E7E1",
      rugAccent: "#D3D0C8",
      sofa: "#CBC9C2",
      sofaShadow: "#A9A79F",
      cushions: ["#2B2B29", "#E9E7E1"],
      wood: "#B4A88F",
      metal: "#2B2B29",
      lampGlow: "#FFF3DC",
      windowLight: "#F1F4F4",
      art: "line",
      artColors: ["#2B2B29"],
      plant: false,
      pendant: false,
      warmth: 0.12,
    },
  },
  {
    id: "industrial",
    name: "Industrial",
    tagline: "Brick, steel and cognac leather",
    description:
      "Exposed brick and blackened steel softened with saddle leather and wool. Raw shell, warm heart.",
    tags: ["Exposed brick", "Black steel", "Leather"],
    palette: ["#4A3A33", "#9C5B3C", "#22211F", "#C9BFAF"],
    budgetBand: "CHF 4.4k – 9.1k",
    spec: {
      wall: "#CFC7B8",
      wallAccent: "#8A5843",
      panel: "brick",
      floor: "#7A6A57",
      floorSeam: "#5E5040",
      rug: "#B8AB94",
      rugAccent: "#8A8272",
      sofa: "#9C5B3C",
      sofaShadow: "#75422A",
      cushions: ["#22211F", "#C9BFAF", "#5E5040"],
      wood: "#5E4630",
      metal: "#22211F",
      lampGlow: "#FFD9A0",
      windowLight: "#E8EBEA",
      art: "abstract",
      artColors: ["#22211F", "#9C5B3C"],
      plant: true,
      pendant: true,
      warmth: 0.45,
    },
  },
  {
    id: "organicmodern",
    name: "Organic Modern",
    tagline: "Curved, earthy, alive",
    description:
      "Soft arcs, oat and sage, raw timber and clay. Nature's palette drawn with a modernist's pencil.",
    tags: ["Curved forms", "Oat & sage", "Raw timber"],
    palette: ["#EAE4D8", "#C8AF8A", "#8A9B84", "#4E4A40"],
    budgetBand: "CHF 3.8k – 7.9k",
    spec: {
      wall: "#EAE4D8",
      wallAccent: "#E0D8C6",
      panel: "arch",
      floor: "#C8AF8A",
      floorSeam: "#AC9268",
      rug: "#DCD4C2",
      rugAccent: "#A9B29A",
      sofa: "#D9D2C2",
      sofaShadow: "#B9B09C",
      cushions: ["#8A9B84", "#C7B9A0", "#4E4A40"],
      wood: "#A08258",
      metal: "#4E4A40",
      lampGlow: "#FFEBC6",
      windowLight: "#EFF3EC",
      art: "botanical",
      artColors: ["#8A9B84", "#6E6455"],
      plant: true,
      pendant: false,
      warmth: 0.3,
    },
  },
  {
    id: "mediterranean",
    name: "Mediterranean",
    tagline: "Whitewash, terracotta, sea air",
    description:
      "Sun-baked plaster, terracotta and olive branches under a bright coastal sky. Holiday, made permanent.",
    tags: ["Whitewash", "Terracotta", "Olive"],
    palette: ["#F0E9DA", "#C0603A", "#7E9BA3", "#5A4632"],
    budgetBand: "CHF 3.5k – 7.4k",
    spec: {
      wall: "#F0E9DA",
      wallAccent: "#E6D9BE",
      panel: "arch",
      floor: "#B98A5C",
      floorSeam: "#9C6F44",
      rug: "#C0603A",
      rugAccent: "#E7D6BC",
      sofa: "#E6DECA",
      sofaShadow: "#C6BCA4",
      cushions: ["#C0603A", "#7E9BA3", "#5A4632"],
      wood: "#8A6540",
      metal: "#8F7443",
      lampGlow: "#FFE0AE",
      windowLight: "#EAF4F6",
      art: "abstract",
      artColors: ["#C0603A", "#7E9BA3"],
      plant: true,
      pendant: true,
      warmth: 0.45,
    },
  },
  {
    id: "darkluxury",
    name: "Dark Luxury",
    tagline: "Velvet, brass and midnight drama",
    description:
      "Deep lacquered green, fluted detail and unapologetic brass. Evening-first rooms with cinema in their veins.",
    tags: ["Velvet", "Brass", "Lacquered green"],
    palette: ["#1F3B33", "#2E5347", "#C8A96E", "#12211D"],
    budgetBand: "CHF 6.2k – 14k",
    spec: {
      wall: "#26443A",
      wallAccent: "#1D362E",
      panel: "arch",
      floor: "#4C3A2B",
      floorSeam: "#382A1E",
      rug: "#1B2F29",
      rugAccent: "#C8A96E",
      sofa: "#2E5347",
      sofaShadow: "#1F3B33",
      cushions: ["#C8A96E", "#12211D", "#7E9C90"],
      wood: "#3B2C1F",
      metal: "#C8A96E",
      lampGlow: "#FFDFA2",
      windowLight: "#DCE4DE",
      art: "geo",
      artColors: ["#C8A96E", "#7E9C90"],
      plant: true,
      pendant: true,
      warmth: 0.55,
    },
  },
  {
    id: "cozy",
    name: "Cozy",
    tagline: "Layered, warm, hug-shaped",
    description:
      "Rust and oat wool, low amber light, more textiles than strictly necessary. The room equivalent of a wood fire.",
    tags: ["Layered wool", "Rust & oat", "Amber light"],
    palette: ["#E5D9C6", "#C89B6E", "#A35E3B", "#6E5B44"],
    budgetBand: "CHF 3.1k – 6.6k",
    spec: {
      wall: "#E5D9C6",
      wallAccent: "#D9C9AE",
      panel: "wainscot",
      floor: "#9C7248",
      floorSeam: "#7E5A36",
      rug: "#C89B6E",
      rugAccent: "#8A5B3A",
      sofa: "#D8C7AC",
      sofaShadow: "#B5A488",
      cushions: ["#A35E3B", "#6E5B44", "#E5D9C6"],
      wood: "#7E5B38",
      metal: "#5A4632",
      lampGlow: "#FFDFA8",
      windowLight: "#F0EEE2",
      art: "line",
      artColors: ["#A35E3B", "#6E5B44"],
      plant: true,
      pendant: true,
      warmth: 0.65,
    },
  },
  {
    id: "classic",
    name: "Classic",
    tagline: "Symmetry, navy and good tailoring",
    description:
      "Wainscoted walls, deep navy upholstery and polished walnut. Rooms your grandchildren will still find correct.",
    tags: ["Wainscot", "Navy", "Walnut"],
    palette: ["#E9E2D2", "#46586E", "#C8A96E", "#5E4025"],
    budgetBand: "CHF 5.2k – 11k",
    spec: {
      wall: "#E9E2D2",
      wallAccent: "#D8CDB4",
      panel: "wainscot",
      floor: "#7E5A38",
      floorSeam: "#644628",
      rug: "#3A4A63",
      rugAccent: "#C8A96E",
      sofa: "#46586E",
      sofaShadow: "#33445A",
      cushions: ["#C8A96E", "#E9E2D2", "#6E3B33"],
      wood: "#5E4025",
      metal: "#8F7443",
      lampGlow: "#FFE5B4",
      windowLight: "#ECF0EE",
      art: "botanical",
      artColors: ["#46586E", "#5E4025"],
      plant: true,
      pendant: true,
      warmth: 0.4,
    },
  },
];

export const STYLE_MAP: Record<string, DesignStyle> = Object.fromEntries(
  STYLES.map((s) => [s.id, s]),
);

/**
 * Derives one of three concept variants from a base style spec.
 * Variant 0 is the canonical style; 1 and 2 remix accents, art and decor
 * so each generation feels like a distinct designer take.
 */
export function makeVariantSpec(spec: RoomStyleSpec, variant: number): RoomStyleSpec {
  if (variant <= 0) return spec;
  const rotate = <T,>(arr: T[], n: number) =>
    arr.length ? arr.map((_, i) => arr[(i + n) % arr.length]) : arr;
  if (variant === 1) {
    return {
      ...spec,
      cushions: rotate(spec.cushions, 1),
      rug: spec.rugAccent,
      rugAccent: spec.rug,
      art: spec.art === "line" ? "abstract" : spec.art === "geo" ? "abstract" : "geo",
      pendant: !spec.pendant,
    };
  }
  return {
    ...spec,
    cushions: rotate(spec.cushions, 2),
    artColors: rotate(spec.artColors, 1),
    art: spec.art === "botanical" ? "line" : "botanical",
    plant: true,
    warmth: Math.min(1, spec.warmth + 0.15),
  };
}

export const VARIANT_NAMES = ["Signature", "Editorial", "Warm Hour"];
export const VARIANT_NOTES = [
  "The canonical read of the style — balanced, true to its source.",
  "A gallery-leaning remix: swapped accents, bolder art, cleaner ceiling line.",
  "Tuned for evenings — deeper warmth, layered lighting, softer textiles.",
];
