import type { DesignStyle, RoomStyleSpec } from "./types";

export const STYLES: DesignStyle[] = [
  {
    id: "scandinavian",
    name: "Scandinavian",
    tagline: "Light, calm, effortless",
    description:
      "Pale oak, soft whites and functional silhouettes. A room that breathes — built around daylight and quiet texture.",
    tags: ["Airy", "Pale oak", "Soft neutrals"],
    palette: ["#EDEAE2", "#D8CFC0", "#B9A98C", "#3D3A34"],
    budgetBand: "$3.2k – $6.8k",
    spec: {
      wall: "#E9E5DC",
      wallAccent: "#DFD9CC",
      panel: "none",
      floor: "#D8C4A4",
      floorSeam: "#C2AC8A",
      rug: "#E3DDD0",
      rugAccent: "#C9C0AE",
      sofa: "#D6D1C6",
      sofaShadow: "#B8B2A5",
      cushions: ["#B9A98C", "#8F8B80", "#E9E5DC"],
      wood: "#C9A876",
      metal: "#3D3A34",
      lampGlow: "#FFE9C4",
      windowLight: "#EAF2F5",
      art: "line",
      artColors: ["#3D3A34", "#B9A98C"],
      plant: true,
      pendant: true,
      warmth: 0.25,
    },
  },
  {
    id: "japandi",
    name: "Japandi",
    tagline: "Wabi-sabi meets nordic restraint",
    description:
      "Low-slung forms, slatted wood and tea-stained neutrals. Every object earns its place; nothing shouts.",
    tags: ["Low profile", "Slatted wood", "Tea tones"],
    palette: ["#E4DCCB", "#B49B72", "#6E5B44", "#2E2A25"],
    budgetBand: "$4.1k – $8.5k",
    spec: {
      wall: "#E2DACA",
      wallAccent: "#D3C6AE",
      panel: "slats",
      floor: "#B99971",
      floorSeam: "#96794F",
      rug: "#D8CDB6",
      rugAccent: "#B8A784",
      sofa: "#A79680",
      sofaShadow: "#84755F",
      cushions: ["#2E2A25", "#D8CDB6", "#6E5B44"],
      wood: "#8A6B44",
      metal: "#2E2A25",
      lampGlow: "#FFE3B8",
      windowLight: "#EDF0EA",
      art: "botanical",
      artColors: ["#6E5B44", "#2E2A25"],
      plant: true,
      pendant: true,
      warmth: 0.35,
    },
  },
  {
    id: "midcentury",
    name: "Mid-Century Modern",
    tagline: "Walnut, mustard and good bones",
    description:
      "Tapered legs, saturated accents and honest walnut. The confident geometry of 1958, tuned for how you live now.",
    tags: ["Walnut", "Saturated accents", "Tapered legs"],
    palette: ["#E8DFCE", "#C46F35", "#5A7058", "#3A2E24"],
    budgetBand: "$4.8k – $9.6k",
    spec: {
      wall: "#E8E1D2",
      wallAccent: "#DCCFB6",
      panel: "none",
      floor: "#8A5F3B",
      floorSeam: "#6F4A2B",
      rug: "#D9C9A8",
      rugAccent: "#C46F35",
      sofa: "#C46F35",
      sofaShadow: "#9A5427",
      cushions: ["#5A7058", "#E8DFCE", "#3A2E24"],
      wood: "#6B4A2E",
      metal: "#B08D4F",
      lampGlow: "#FFDFA8",
      windowLight: "#EDF2EE",
      art: "geo",
      artColors: ["#C46F35", "#5A7058", "#3A2E24"],
      plant: true,
      pendant: true,
      warmth: 0.4,
    },
  },
  {
    id: "minimalist",
    name: "Minimalist",
    tagline: "Nothing extra, everything intentional",
    description:
      "A near-monochrome envelope where proportion does the talking. Storage disappears; light and shadow furnish the room.",
    tags: ["Monochrome", "Hidden storage", "Negative space"],
    palette: ["#F2F1EE", "#DBD9D4", "#9E9C96", "#2B2B29"],
    budgetBand: "$2.9k – $6.2k",
    spec: {
      wall: "#F0EEE9",
      wallAccent: "#E6E4DE",
      panel: "none",
      floor: "#DCD7CD",
      floorSeam: "#C6C0B4",
      rug: "#E9E7E1",
      rugAccent: "#D3D0C8",
      sofa: "#CBC9C2",
      sofaShadow: "#A9A79F",
      cushions: ["#2B2B29", "#E9E7E1"],
      wood: "#B4A88F",
      metal: "#2B2B29",
      lampGlow: "#FFF3DC",
      windowLight: "#F1F4F4",
      art: "line",
      artColors: ["#2B2B29"],
      plant: false,
      pendant: false,
      warmth: 0.12,
    },
  },
  {
    id: "industrial",
    name: "Industrial Loft",
    tagline: "Brick, steel and cognac leather",
    description:
      "Exposed brick and blackened steel softened with saddle leather and wool. Raw shell, warm heart.",
    tags: ["Exposed brick", "Black steel", "Leather"],
    palette: ["#4A3A33", "#9C5B3C", "#22211F", "#C9BFAF"],
    budgetBand: "$4.4k – $9.1k",
    spec: {
      wall: "#CFC7B8",
      wallAccent: "#8A5843",
      panel: "brick",
      floor: "#7A6A57",
      floorSeam: "#5E5040",
      rug: "#B8AB94",
      rugAccent: "#8A8272",
      sofa: "#9C5B3C",
      sofaShadow: "#75422A",
      cushions: ["#22211F", "#C9BFAF", "#5E5040"],
      wood: "#5E4630",
      metal: "#22211F",
      lampGlow: "#FFD9A0",
      windowLight: "#E8EBEA",
      art: "abstract",
      artColors: ["#22211F", "#9C5B3C"],
      plant: true,
      pendant: true,
      warmth: 0.45,
    },
  },
  {
    id: "bohemian",
    name: "Bohemian",
    tagline: "Collected, layered, alive",
    description:
      "Terracotta, rattan and a jungle of green. Rooms that look gathered over a decade of good travel.",
    tags: ["Terracotta", "Rattan", "Plants"],
    palette: ["#E7D6BC", "#C0603A", "#8A9B6B", "#5A4632"],
    budgetBand: "$3.4k – $7.3k",
    spec: {
      wall: "#EBDFC9",
      wallAccent: "#E0CCA9",
      panel: "arch",
      floor: "#B98A5C",
      floorSeam: "#9C6F44",
      rug: "#C0603A",
      rugAccent: "#E7D6BC",
      sofa: "#D9C4A2",
      sofaShadow: "#B39F7D",
      cushions: ["#C0603A", "#8A9B6B", "#5A4632"],
      wood: "#8A6540",
      metal: "#8F7443",
      lampGlow: "#FFE0AE",
      windowLight: "#F2EFE2",
      art: "botanical",
      artColors: ["#8A9B6B", "#C0603A"],
      plant: true,
      pendant: true,
      warmth: 0.5,
    },
  },
  {
    id: "artdeco",
    name: "Art Deco Revival",
    tagline: "Velvet, brass and drama",
    description:
      "Deep lacquered green, fluted detail and unapologetic brass. Evening-first rooms with cinema in their veins.",
    tags: ["Velvet", "Brass", "Fluted detail"],
    palette: ["#1F3B33", "#2E5347", "#C8A96E", "#12211D"],
    budgetBand: "$6.2k – $14k",
    spec: {
      wall: "#26443A",
      wallAccent: "#1D362E",
      panel: "arch",
      floor: "#4C3A2B",
      floorSeam: "#382A1E",
      rug: "#1B2F29",
      rugAccent: "#C8A96E",
      sofa: "#2E5347",
      sofaShadow: "#1F3B33",
      cushions: ["#C8A96E", "#12211D", "#7E9C90"],
      wood: "#3B2C1F",
      metal: "#C8A96E",
      lampGlow: "#FFDFA2",
      windowLight: "#DCE4DE",
      art: "geo",
      artColors: ["#C8A96E", "#7E9C90"],
      plant: true,
      pendant: true,
      warmth: 0.55,
    },
  },
  {
    id: "coastal",
    name: "Coastal Calm",
    tagline: "Driftwood, linen, horizon blue",
    description:
      "Washed timber and sea-glass blues under crisp white. The exhale of a shore house, minus the seashell kitsch.",
    tags: ["Washed oak", "Linen", "Sea glass"],
    palette: ["#F0EEE6", "#B9CBC9", "#7E9BA3", "#5B6B70"],
    budgetBand: "$3.6k – $7.8k",
    spec: {
      wall: "#EFEDE4",
      wallAccent: "#DEE4DD",
      panel: "wainscot",
      floor: "#D3C3A6",
      floorSeam: "#BBA983",
      rug: "#D9E0DA",
      rugAccent: "#9FB6B4",
      sofa: "#E4E1D6",
      sofaShadow: "#C2BFB2",
      cushions: ["#7E9BA3", "#B9CBC9", "#5B6B70"],
      wood: "#BCA378",
      metal: "#5B6B70",
      lampGlow: "#FFF0CE",
      windowLight: "#E4F1F4",
      art: "abstract",
      artColors: ["#7E9BA3", "#B9CBC9"],
      plant: true,
      pendant: false,
      warmth: 0.2,
    },
  },
];

export const STYLE_MAP: Record<string, DesignStyle> = Object.fromEntries(
  STYLES.map((s) => [s.id, s]),
);

/**
 * Derives one of three concept variants from a base style spec.
 * Variant 0 is the canonical style; 1 and 2 remix accents, art and decor
 * so each generation feels like a distinct designer take.
 */
export function makeVariantSpec(spec: RoomStyleSpec, variant: number): RoomStyleSpec {
  if (variant <= 0) return spec;
  const rotate = <T,>(arr: T[], n: number) =>
    arr.length ? arr.map((_, i) => arr[(i + n) % arr.length]) : arr;
  if (variant === 1) {
    return {
      ...spec,
      cushions: rotate(spec.cushions, 1),
      rug: spec.rugAccent,
      rugAccent: spec.rug,
      art: spec.art === "line" ? "abstract" : spec.art === "geo" ? "abstract" : "geo",
      pendant: !spec.pendant,
    };
  }
  return {
    ...spec,
    cushions: rotate(spec.cushions, 2),
    artColors: rotate(spec.artColors, 1),
    art: spec.art === "botanical" ? "line" : "botanical",
    plant: true,
    warmth: Math.min(1, spec.warmth + 0.15),
  };
}

export const VARIANT_NAMES = ["Signature", "Editorial", "Warm Hour"];
export const VARIANT_NOTES = [
  "The canonical read of the style — balanced, true to its source.",
  "A gallery-leaning remix: swapped accents, bolder art, cleaner ceiling line.",
  "Tuned for evenings — deeper warmth, layered lighting, softer textiles.",
];
